// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.Data.EF;

namespace MovieApp.Data.Migrations
{
    [DbContext(typeof(MovieAppContext))]
    [Migration("20191012170036_add some fixes")]
    partial class addsomefixes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieApp.Data.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("MovieApp.Data.Entities.ActorMovies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int?>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("ActorsId");

                    b.HasIndex("MovieId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ActorMovies");
                });

            modelBuilder.Entity("MovieApp.Data.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MovieApp.Data.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieApp.Data.Entities.MovieGenres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int?>("GenreId1")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("GenreId1");

                    b.HasIndex("MovieId");

                    b.HasIndex("MovieId1");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("MovieApp.Data.Entities.ActorMovies", b =>
                {
                    b.HasOne("MovieApp.Data.Entities.Actor", null)
                        .WithMany("ActorMovies")
                        .HasForeignKey("ActorId")
                        .HasConstraintName("FK_AM_Actor")
                        .IsRequired();

                    b.HasOne("MovieApp.Data.Entities.Actor", "Actors")
                        .WithMany()
                        .HasForeignKey("ActorsId");

                    b.HasOne("MovieApp.Data.Entities.Movie", null)
                        .WithMany("ActorMovies")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("FK_AM_Movie")
                        .IsRequired();

                    b.HasOne("MovieApp.Data.Entities.Movie", "Movies")
                        .WithMany()
                        .HasForeignKey("MoviesId");
                });

            modelBuilder.Entity("MovieApp.Data.Entities.MovieGenres", b =>
                {
                    b.HasOne("MovieApp.Data.Entities.Genre", null)
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("FK_MG_G")
                        .IsRequired();

                    b.HasOne("MovieApp.Data.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId1");

                    b.HasOne("MovieApp.Data.Entities.Movie", null)
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("FK_MG_M")
                        .IsRequired();

                    b.HasOne("MovieApp.Data.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId1");
                });
#pragma warning restore 612, 618
        }
    }
}
